FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y python3 python3-dev  \
    libffi-dev libxml2-dev libxslt1-dev zlib1g-dev libssl-dev wget

RUN mkdir -p /scrapyrt/src /scrapyrt/project
RUN mkdir -p /var/log/scrapyrt

RUN wget -O /tmp/get-pip.py "https://bootstrap.pypa.io/get-pip.py" && \
    python3 /tmp/get-pip.py "pip==19.3.1" && \
    rm /tmp/get-pip.py

ADD . /scrapyrt/src
RUN pip install scrapy && pip install scrapyrt && pip install pymongo

WORKDIR /scrapyrt/project

ENTRYPOINT ["scrapyrt", "-i", "0.0.0.0"]

EXPOSE 9080
